version: 2.1

jobs:
  create_zip:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Crear tag y zip"
      - run: git config --global user.email "<< pipeline.id >>@correo.com"
      - run: git config --global user.name "<< pipeline.id >>"
      - run: git tag -a << pipeline.id >> -m 'version << pipeline.id >>'
      - run: git tag
      - run: sudo apt-get install zip
      - run: zip -r helloworld.zip .
      - run: ls

workflows:
  test_zip:
    jobs:
      - create_zip