version: 2.1

jobs:
  setup_git:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Crear tag"
      - run: git config --global user.email "<< pipeline.id >>@correo.com"
      - run: git config --global user.name "<< pipeline.id >>"
      - run: git tag -a << pipeline.id >> -m 'version << pipeline.id >>'
      - run: git tag
      - run: git remote add origin https://github.com/SebastianCl/hello-world-newcombin.git
      - run: git push --tags

  create_zip:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Crear zip"
      - run: sudo apt-get install zip
      - run: zip -r helloworld.zip .
      - run: ls
      - store_artifacts:
          path: ./helloworld.zip
          destination: << pipeline.id >>


workflows:
  challenge_3:
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - master
    jobs:
      - setup_git
      - create_zip:
          requires:
            - setup_git